"""
Django settings for meiduo_mall project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path


# "应用名.模型名"
AUTH_USER_MODEL = "users.User"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-dhlx2z7fa*jj_#6y3oa$sia==$1nj9s4930fed8)_kz)b18)!*"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "www.meiduo.site",
    "meiduo.site",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'apps.users.apps.UsersConfig',
    "celery_tasks",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "meiduo_mall.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',  # 使用 Jinja2
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # 全局模板目录
        'APP_DIRS': False,
        'OPTIONS': {
            'environment': 'utils.jinja2.environment',  # 指定 Jinja2 环境
            'context_processors': [
                "django.template.context_processors.request",  # 注入 request
                "django.contrib.auth.context_processors.auth",  # 注入 user
                "django.contrib.messages.context_processors.messages",  # 注入 messages
            ]
        },
    },
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "meiduo_mall.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 设置为 MySQL
        'NAME': 'meiduo_mall',          # 您的数据库名称
        'USER': 'root',               # 您的用户名
        'PASSWORD': 'Ljh721122',           # 您的密码
        'HOST': 'localhost',                   # 数据库主机
        'PORT': '3306',                        # MySQL 的默认端口
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# ------------ Static Settings -------------

# 静态资源访问前缀，访问静态文件时使用http://127.0.0.1:8000/static/xxx
STATIC_URL = '/static/'

# 开发环境使用你的 static 目录，告诉 Django 静态文件放在哪里
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# 部署时收集静态文件的目录，这个目录 Django collectstatic 会用（生产环境会用 nginx 指向 static_root 来加载静态文件，现在先不管也没关系，但写上比较规范。）
STATIC_ROOT = os.path.join(BASE_DIR, "static_root")



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -------- Redis 缓存配置 --------
CACHES = {
    "default": {  # 0 号库
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SERIALIZER": "django_redis.serializers.pickle.PickleSerializer",
        }
    },
    "session": {  # 1 号库（专门存 Session）
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },

    "verify_codes": {  # 2 号库（验证码专用）
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },

}

# -------- 指定 Session 使用 Redis session --------
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "session"



# 容联云通讯短信配置
RONG_LIAN = {
    "accId": "2c94811c9860a9c4019ac5ab8beb5ac1",
    "accToken": "e0b639b11fc64f33b9bc1c8cd6c0814f",
    "appId": "2c94811c9860a9c4019ac5ab8cab5ac8",
}

# -------- 日志模块 ----------
LOG_DIR = os.path.join(BASE_DIR, "logs")
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    # 日志格式定义
    "formatters": {
        "standard": {
            "format": "[%(asctime)s] [%(levelname)s] [%(name)s:%(lineno)d] %(message)s"
        },
        "simple": {
            "format": "[%(levelname)s] %(message)s"
        }
    },

    # Handlers：日志输出到哪里
    "handlers": {
        # 写入 debug/info/warning 日志
        "default": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "django.log"),
            "when": "midnight",
            "backupCount": 10,
            "encoding": "utf-8",
            "formatter": "standard",
        },

        # 写入 error 日志
        "error": {
            "level": "ERROR",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "error.log"),
            "when": "midnight",
            "backupCount": 10,
            "encoding": "utf-8",
            "formatter": "standard",
        },

        # 控制台输出（开发环境）
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple"
        },
    },

    # 具体 logger 设置
    "loggers": {
        # 默认 Django 日志
        "django": {
            "handlers": ["default", "console"],
            "level": "INFO",
            "propagate": True
        },

        # 专门记录错误
        "django.request": {
            "handlers": ["error"],
            "level": "ERROR",
            "propagate": False,
        },

        # 你的项目 logger
        "meiduo": {
            "handlers": ["default", "console"],
            "level": "DEBUG",
            "propagate": True
        }
    }
}

# # =========== Celery 配置 ===========
# # 使用 Redis 作为 Celery broker（任务调度队列）
# CELERY_BROKER_URL = "redis://127.0.0.1:6379/5"
#
# # Celery worker 执行结果存储（可不需要，但建议加上）
# CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/6"
#
# # 时区与 Django 保持一致
# CELERY_TIMEZONE = "Asia/Shanghai"